#pragma once
#include <memory>
#include <iostream>
#include <array>
#include <cstring>
#include <cassert>
#include <algorithm>
#include <sstream>
#include <iomanip>
#include <fstream>
#include <vector>
#include <map>
#include <unordered_map>
#include <source_location>
#include <exception>
#include <stdexcept>
#include <deque>
#include <cassert>
#include <set>
#include <cstdint>
#include <cstdlib>
#include <bitset>
#include <cmath>
#include <GL/glew.h> // for access to OpenGL API declarations 
#include <GLFW/glfw3.h>
#include <filesystem>
#include <cstdint>
#include <time.h>
#include <thread>
#include <mutex>
#include "NFmath.h"
